; ***  WattWächter Build Environments  ***

; *** WattWächter Wifi/USB (ESP8266, 1M Flash) - SML Smartmeter Lesekopf
[env:wattwaechter_wifi_usb]
board                       = esp8266_1M
build_flags                 = ${env.build_flags}
                              -DWATTWAECHTER_WIFI_USB
                              -DOTA_URL='"http://upgrade.smartcircuits.de/wattwaechter/latest/tasmota.bin.gz"'

; *** WattWächter.tasmota (ESP32-C6-Mini, 8M Flash) - SML Smartmeter Lesekopf
[env:wattwaechter_esp32c6]
extends                     = env:tasmota32_base
board                       = esp32c6_8M
build_flags                 = ${env:tasmota32_base.build_flags}
                              -DWATTWAECHTER_ESP32C6
                              -DCONFIG_NIMBLE_CPP_IDF
                              -DOTA_URL='"http://upgrade.smartcircuits.de/wattwaechter/latest/tasmota32c6.bin"'
lib_extra_dirs              = ${env:tasmota32_base.lib_extra_dirs}
                              lib/libesp32_div
lib_ignore                  = ${env:tasmota32_base.lib_ignore}
                              Micro-RTSP
